# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-20 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataFb',
        ),
    ]
